version: "3.9"
services:
  api:
    ports:
      - "8080:8000"
    environment:
      - JWT_ALGORITHM=HS256
  frontend:
    ports:
      - "3001:3000"
  db:
    ports:
      - "5435:5432"
  redis:
    ports:
      - "6380:6379"
  nginx:
    ports:
      - "8088:80"
  minio:
    ports:
      - "9010:9000"
      - "9011:9001"
